---
# tasks file for prometheus-node-exporter

- name: Donwload Node Exporter
  get_url:
     url: https://github.com/prometheus/node_exporter/releases/download/v0.15.2/node_exporter-0.15.2.linux-amd64.tar.gz
     dest: /opt/node_exporter.tar.gz
     mode: 0440

- name: Create monitoring folder
  file:
    path: /opt/monitoring
    state: directory
    mode: 0755

- name: Extract Node Exporter archive
  unarchive:
    src: /opt/node_exporter.tar.gz
    dest: /opt/monitoring/

- name: Copy node_exporter service file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/
    owner: root
    group: root

- name: Ensure node_exporter starts and run on startup
  service:
    name: node_exporter
    state: restarted
    enabled: yes  
